cookie:
  expiry_days: 30
  key: null
  name: auth_session
credentials:
  usernames: {}
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: ''
    redirect_url: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
